# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2
  postfix: 0621
  location: westus
  environment: dev
  enable_aml_computecluster: true

  # Azure DevOps 
  ado_service_connection_rg: Azure-ARM-Dev
  ado_service_connection_aml_ws: Azure-ARM-Dev

  # IaC
  resource_group: azureml-examples-rg
  aml_workspace: main 
  application_insights: maininsights3940d807586b
  key_vault: mainkeyvaultaa801245b95c
  container_registry: e7fd97c2665e408bab3c1c126576f89e
  storage_account: mainstorage5338948febc34

  # Terraform
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure/terraform
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf-state
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tfstate
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
