# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../../../../config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../../../../config-infra-dev.yml
- name: version
  value: aml-cli-v2

resources:
  repositories:
    - repository: mlops-templates  # Template Repo
      name: Azure/mlops-templates # need to change org name from "Azure" to your own org
      endpoint: github-connection # need to set up and hardcode
      type: github
      ref: feature/sdkv2-samer
      
trigger:
- none

pool:
  vmImage: ubuntu-20.04

stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      timeoutInMinutes: 120 # how long to run the job before automatically cancelling
      steps:
      - checkout: self
        path: s/
      - checkout: mlops-templates
        path: s/templates/
      - template: templates/${{ variables.version }}/install-az-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/install-aml-cli.yml@mlops-templates
      - template: templates/${{ variables.version }}/connect-to-workspace.yml@mlops-templates
      - template: templates/${{ variables.version }}/register-environment.yml@mlops-templates
        parameters:
          build_type: conda
          environment_name: taxi-train-env
          environment_file: classical/python-sdk-v2/mlops/azureml/train/train-env.yml
          enable_monitoring: $(enable_monitoring)
      - template: templates/python-sdk-v2/register-data-asset.yml@mlops-templates
        parameters:
          dataAssetName: taxi-data
          dataAssetDescription: taxi-training-data
          dataAssetLocalPath: classical/python-sdk-v2/data/taxi-data.csv
          dataAssetType: uri_file
      - template: templates/python-sdk-v2/run-pipeline.yml@mlops-templates
        parameters: 
          enable_monitoring: $(enable_monitoring)