name: deploy-model-training-pipeline

on: 
  workflow_dispatch:
jobs:
  get-config:
      uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
      with:
        file_name: config-infra-prod.yml
  create-compute-standard:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: cpu-cluster
        size: STANDARD_DS3_V2
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
  create-compute-large:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: cpu-cluster-lg
        size: Standard_D14_v2
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
   create-compute-gpu:
      needs: get-config
      uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
      with:
        cluster_name: gpu-cluster
        size: Standard_NC6
        min_instances: 0
        max_instances: 1
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
      secrets:
          creds: ${{secrets.AZURE_CREDENTIALS}}
   register-environment:
      needs: [get-config,create-compute-standard,create-compute-large,create-compute-gpu]
      uses: ./.github/workflows/register-environment.yml
      with:
        resource_group: ${{ needs.get-config.outputs.resource_group }}
        workspace_name: ${{ needs.get-config.outputs.aml_workspace }}     
        environment_file: mlops/azureml/train/train-env.yaml 
        dockerfile-location: data-science/environments/training
      secrets:
        creds: ${{secrets.AZURE_CREDENTIALS}}
