$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: taxi-online-dp
endpoint_name: taxi-online-endpoint
model:
  name: azureml:taxi-model@latest
  type: mlflow_model
instance_type: Standard_DS2_v2
instance_count: 1